name: analysis-runner
channels:
  - cpg
  - bioconda
  - conda-forge
dependencies:
  - pip
  - analysis-runner  # Not yet in pypi.
  - cpg-utils  # Not yet in pypi.
  - pip:
    - airtable-python-wrapper
    - black
    - bump2version
    - cpg-hail
    - flake8
    - flake8-bugbear
    - flask
    - google-api-python-client==2.10.0
    - google-auth==1.27.0
    - google-cloud-logging==3.0.0
    - google-cloud-pubsub==2.3.0
    - google-cloud-secret-manager==2.2.0
    - google-cloud-storage==1.25.0
    - kubernetes
    - pre-commit
    - pulumi-gcp
    - pylint
    - requests
    - tabulate
