name: analysis-runner
channels:
  - cpg
  - bioconda
  - conda-forge
dependencies:
  - black
  - cpg-utils
  - flake8
  - flake8-bugbear
  - flask
  - google-auth=1.24.0
  - google-api-python-client=2.10.0
  - google-cloud-pubsub=2.3.0
  - google-cloud-secret-manager=2.2.0
  - google-cloud-storage=1.38.0
  - hail
  - pre-commit
  - pylint
  - python-kubernetes=12.0.1
  - python=3.9
  - bump2version
  - requests
  - tabulate
  - pip
  - pip:
    - airtable-python-wrapper==0.15.1
    - pulumi-gcp
