name: analysis-runner
channels:
  - cpg
  - bioconda
  - conda-forge
dependencies:
  - black
  - flake8
  - flake8-bugbear
  - google-cloud-secret-manager=2.2.0
  - hail=0.2.61.devd9fcfb5
  - pre-commit
  - pylint
  - python-kubernetes=12.0.1
  - python=3.7
  - bump2version
  - requests
  - pip:
    - pulumi-gcp
